version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3307:3306' # added in case an external app or tool running outside of Docker needs to connect. It is 
                    # not necessary for the connection to my-phpadmin and my-wordpreess
    volumes:
      - mysql-db-backup:/var/lib/mysql
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: linsenmitlentejas
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress 
      MYSQL_PASSWORD: wordpress
    networks:
      - mysql-network

  phpadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: my-phpadmin
    environment:
      PMA_HOST: mysql
    ports:
      - '8081:80'
    depends_on:
      - mysql
    networks:
      - mysql-network


  wordpress:    
    image: wordpress:5.4
    restart: always
    container_name: wordpress
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - mysql-network
  
volumes:
  mysql-db-backup:

networks:
  mysql-network:
    driver: bridge